name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: formation_docker
      run: docker build . --file Dockerfile --tag amadouguindo/cheers2019:$(date +%s)
